# Generated by Django 5.1.5 on 2025-01-27 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Blog_ID', models.CharField(max_length=10)),
                ('BlogTitle', models.CharField(max_length=50)),
                ('Description', models.CharField(max_length=500)),
                ('Author', models.CharField(max_length=100)),
                ('Date', models.CharField(max_length=25)),
            ],
        ),
    ]
