# Generated by Django 5.1.5 on 2025-01-30 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='Description',
            field=models.TextField(max_length=500),
        ),
    ]
